# Generated by Django 6.0.6 on 2026-07-07 17:52

import pgvector.django.halfvec
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_learning_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='embedding',
            field=pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=768, null=True),
        ),
    ]
