# Generated by Django 6.0.6 on 2026-07-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_add_generation_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
