# Generated by Django 6.0.6 on 2026-07-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubjectprogress',
            name='selection_pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
