# Generated by Django 6.0.6 on 2026-07-12 00:41

import pgvector.django.halfvec
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_selection_pending_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='embedding',
            field=pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
